backend:
  name: git-gateway
  branch: main # Production branch
  site_url: https://your-site-name.netlify.app # Replace with your actual site URL

# Use editorial workflow for branch-based content management
publish_mode: editorial_workflow

# Configure branch preview settings
# This creates a separate branch for drafts/previews
# Netlify will automatically create a preview deployment for this branch
editorial_workflow:
  # Drafts are saved to a separate branch with this prefix
  branch_prefix: "cms-preview"

# Media folder where uploaded images will be stored
media_folder: "uploads"
public_folder: "/uploads"

# Media library settings for better image management
media_library:
  name: uploadcare
  config:
    publicKey: "your-uploadcare-public-key" # Replace with your Uploadcare public key
    multiple: true
    tabs: "file camera url facebook gdrive gphotos"
    effects: "crop,rotate,enhance,grayscale"
    imageShrink: "2000x2000"
    previewStep: true
    clearable: true

# Create a preview context for the CMS branch
# This will create a separate deployment for the CMS branch
# Netlify will automatically create a preview URL for this branch
display_url: https://main--your-site-name.netlify.app # Replace with your actual site URL

# Collections define the structure for content types
collections:
  - name: "portfolio"
    label: "Portfolio Items"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    preview_path: "html/gallery.html"
    editor:
      preview: true
    # Define fields for portfolio items
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured", name: "featured", widget: "boolean", default: false }
      
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about.md"
        label: "About Page"
        name: "about"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
      
      - file: "content/services.md"
        label: "Services Page"
        name: "services"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }